# Generated by Django 5.2.4 on 2026-10-05 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_drop_area_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airportprefixarea',
            options={'ordering': ['sequence', 'area', 'prefix'], 'verbose_name': '前缀区域', 'verbose_name_plural': '前缀区域'},
        ),
    ]
