"""
Django settings for mtws_system project.

Generated by 'django-admin startproject' using Django 4.2.
"""

from pathlib import Path
import os
import logging
from datetime import datetime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# 自定义日志处理器：按日期创建文件，避免重命名冲突
class DailyFileHandler(logging.FileHandler):
    """
    按日期创建日志文件的处理器，避免重命名正在使用的文件
    文件名格式：mtws.log.2025-09-28
    """
    def __init__(self, filename, mode='a', encoding=None, delay=False, backup_count=7):
        self.base_filename = filename
        self.backup_count = backup_count
        self.current_date = None
        # 日志目录是运行时产物，不进 git；首次启动时必须自动创建。
        Path(self.base_filename).parent.mkdir(parents=True, exist_ok=True)
        # 初始化时使用当前日期的文件名
        current_filename = self._get_current_filename()
        super().__init__(current_filename, mode, encoding, delay)
    
    def _get_current_filename(self):
        """根据当前日期生成文件名"""
        today = datetime.now().strftime('%Y-%m-%d')
        base_path = Path(self.base_filename)
        base_path.parent.mkdir(parents=True, exist_ok=True)
        return str(base_path.parent / f"{base_path.stem}.{today}{base_path.suffix}")
    
    def emit(self, record):
        """写入日志记录，检查是否需要切换文件"""
        today = datetime.now().strftime('%Y-%m-%d')
        
        # 如果日期变化，切换到新文件
        if self.current_date != today:
            self.current_date = today
            new_filename = self._get_current_filename()
            
            # 关闭当前文件
            if self.stream:
                self.stream.close()
                self.stream = None
            
            # 切换到新文件
            self.baseFilename = new_filename
            
            # 清理旧文件
            self._cleanup_old_files()
        
        # 写入日志
        super().emit(record)
    
    def _cleanup_old_files(self):
        """清理超过保留天数的旧日志文件"""
        try:
            base_path = Path(self.base_filename)
            log_dir = base_path.parent
            pattern = f"{base_path.stem}.????-??-??{base_path.suffix}"
            
            # 找到所有匹配的日志文件
            log_files = list(log_dir.glob(pattern))
            
            # 按修改时间排序，保留最新的backup_count个文件
            if len(log_files) > self.backup_count:
                log_files.sort(key=lambda x: x.stat().st_mtime, reverse=True)
                for old_file in log_files[self.backup_count:]:
                    try:
                        old_file.unlink()
                    except OSError:
                        pass  # 忽略删除失败的文件
        except Exception:
            pass  # 忽略清理过程中的错误

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mtws-secret-key-change-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 内网统一入口会把局域网 IP 写进 Host（如 10.88.24.24:8000）。
# 通配允许席位机用 IP 访问；本系统仅部署在局域网。
ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 项目应用
    'core',
    'parsers', 
    'api',
    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # 自定义中间件（用于时间模式处理）
    'core.middleware.TimeModelMiddleware',
]

ROOT_URLCONF = 'mtws_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'web.context_processors.alert_colors',
            ],
        },
    },
]

WSGI_APPLICATION = 'mtws_system.wsgi.application'

# Database
# default 是配置库。runtime 是实况、预报、航班、告警结果这些生产库。
_SQLITE_DIR = BASE_DIR.parent / 'data' / 'sqlite_database'
_SQLITE_OPTIONS = {'timeout': 30}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _SQLITE_DIR / 'mtws_config.db',
        'OPTIONS': _SQLITE_OPTIONS,
    },
    'runtime': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _SQLITE_DIR / 'mtws_runtime.db',
        'OPTIONS': _SQLITE_OPTIONS,
    },
}
DATABASE_ROUTERS = ['mtws_system.db_router.MtwsRouter']
MIGRATION_MODULES = {
    'core': 'mtws_migrations.core',
    'parsers': 'mtws_migrations.parsers',
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            '()': DailyFileHandler,
            'filename': BASE_DIR.parent / 'logs' / 'mtws.log',
            'encoding': 'utf-8',
            'delay': True,
            'backup_count': 7,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'mtws': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# 告警等级配色（与主页甘特条带同色相）。各处自行叠加透明度/字体，勿在此写 alpha。
ALERT_COLORS = {
    'R': {'hex': '#e74c3c', 'rgb': '231, 76, 60'},
    'Y': {'hex': '#f39c12', 'rgb': '243, 156, 18'},
    'G': {'hex': '#27ae60', 'rgb': '39, 174, 96'},
    'N': {'hex': '#95a5a6', 'rgb': '149, 165, 166'},
}

# MTWS 项目特定配置
MTWS_CONFIG = {
    # 时间模式配置
    'TIME_MODES': {
        'current': {
            'name': '当前时间模式',
            'description': '使用系统当前时间进行处理',
            'url_prefix': 'current',
        },
        'test': {
            'name': '测试时间模式', 
            'description': '使用固定测试时间进行处理',
            'url_prefix': 'test',
            'fixed_time_utc': '2025-09-23 21:40:00',  # UTC时间
        }
    },
    
    # 数据源配置
    'DATA_SOURCE': {
        'type': 'api',  # 'api'
        'csv_config': {
            'data_path': BASE_DIR.parent / 'data' / 'raw'
        },
        'api_config': {
            'flight_endpoint': '',
            'metar_endpoint': '',
            'taf_endpoint': '',
            'auth_token': '',
            'timeout': 30
        }
    },
    
    # 数据保留配置
    'DATA_RETENTION': {
        'metar_max_records': 5000,
        'taf_max_records': 5000,
        'taf_cleanup_batch_size': 500,
        'flight_max_records': 1000,
        'metar_popup_max_records': 5000,
        'cleanup_batch_size': 1000,
    },
    
    # 缓存配置
    'CACHE_TIMEOUT': {
        'default_data': 300,  # 5分钟
        'search_data': 600,   # 10分钟
        'config_data': 3600,  # 1小时
    },
    
    # 航班数据状态配置
    'FLIGHT_DATA_STATUS': {
        'last_success_time': None,      # 最后成功获取时间
        'last_attempt_time': None,      # 最后尝试获取时间
        'is_available': True            # 数据是否可用
    },
    
    # 飞机停场解析器配置
    'AIRCRAFT_PARKING_CONFIG': {
        'PAST_HOURS': 72,               # 过去小时数
        'CURRENT_TIME_OFFSET': 0,       # 当前时间偏移（小时）
        'CARRIER_CODE': 'O3',           # 承运人代码
        'MAX_RECORDS': 800              # 最大保留记录数
    },
    
    # 弹窗配置
    'POPUP_CONFIG': {
        'PARKING_WEATHER_TYPES': ['S', 'F', 'I', 'G', 'H'],  # 停场类弹窗需要判断的天气类型
        'POPUP_VALIDITY_HOURS': 6,  # 弹窗有效期（小时）
        'SNOOZE_DURATION_MINUTES': 10,  # 稍后处理延迟时间（分钟）
        'CHART_DEFAULT_HOURS': 3  # 弹窗图表默认显示小时数
    },

    # 实况入库异常告警配置
    'METAR_IMPORT_ALERT': {
        'CREATED_AT_MINUTES': 70,         # 入库时间超过此分钟数则触发告警
        'OBSERVATION_TIME_MINUTES': 90,   # 观测时间超过此分钟数则触发告警
    },

    # 预报入库异常告警配置
    'TAF_IMPORT_ALERT': {
        'TAF_ISSUE_LEEWAY_MINUTES': 30,   # 告警判断公式中的 m 值（分钟），预留的报文发布宽限时间
    },
}

# 缓存配置
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'mtws-cache',
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 10000,
            'CULL_FREQUENCY': 3,
        }
    }
}
